// Slot key format: "<group>:<kind>:<value>", e.g. "player:image:Assets/custom/player/mercury.png".
// For ring glow variants, append ":glow" (e.g. "ring:color:#ff3b3b:glow").
export const SLOT_CONFIG = {
  defaultRequirement: {
    unlocked: true,
  },
  overrides: {
    'player:default': { unlocked: true },
    'player:custom': { stageId: 'stage1', minScore: 60 },
    'obstacle:default': { unlocked: true },
    'ring:default': { unlocked: true },
    'player:color:#ff3b3b': { stageId: 'stage1', minScore: 10 },
    'player:color:#ff5ca8': { stageId: 'stage1', minScore: 20 },
    'player:color:#ff9b2f': { stageId: 'stage1', minScore: 30 },
    'player:color:#ffe44d': { stageId: 'stage1', minScore: 40 },
    'player:color:#a6ff4d': { stageId: 'stage1', minScore: 50 },
    'player:color:#7cd4ff': { stageId: 'stage1', minScore: 60 },
    'player:image:Assets/custom/player/mercury.png': { stageId: 'stage1', minScore: 10 },
    'player:image:Assets/custom/player/venus.png': { stageId: 'stage1', minScore: 30 },
    'player:image:Assets/custom/player/earth.png': { stageId: 'stage1', minScore: 50 },
    'player:image:Assets/custom/player/mars.png': { stageId: 'stage1', minScore: 60 },
    'player:image:Assets/custom/player/jupiter.png': { stageId: 'stage2', minScore: 10 },
    'player:image:Assets/custom/player/saturn.png': { stageId: 'stage2', minScore: 20 },
    'player:image:Assets/custom/player/uranus.png': { stageId: 'stage2', minScore: 30 },
    'player:image:Assets/custom/player/pluto.png': { stageId: 'stage2', minScore: 40 },
    'player:image:Assets/custom/player/cookie/berry.png': { stageId: 'stage1', minScore: 10 },
    'player:image:Assets/custom/player/cookie/choco.png': { stageId: 'stage1', minScore: 30 },
    'player:image:Assets/custom/player/cookie/gukwha.png': { stageId: 'stage1', minScore: 50 },
    'player:image:Assets/custom/player/cookie/rainbow.png': { stageId: 'stage1', minScore: 60 },
    'player:image:Assets/custom/player/cookie/sharbre.png': { stageId: 'stage2', minScore: 10 },
    'player:image:Assets/custom/player/cookie/완전초코.png': { stageId: 'stage2', minScore: 30 },
    'player:image:Assets/custom/player/cookie/잼쿠기.png': { stageId: 'stage2', minScore: 50 },
    'player:image:Assets/custom/player/cookie/마카롱.png': { stageId: 'stage2', minScore: 60 },
    'player:image:Assets/custom/player/slice/라임.png': { stageId: 'stage1', minScore: 30 },
    'player:image:Assets/custom/player/slice/레몬.png': { stageId: 'stage1', minScore: 60 },
    'player:image:Assets/custom/player/slice/수박.png': { stageId: 'stage2', minScore: 30 },
    'player:image:Assets/custom/player/slice/오렌지.png': { stageId: 'stage2', minScore: 60 },
    'player:image:Assets/custom/player/slice/오이.png': { stageId: 'stage3', minScore: 10 },
    'player:image:Assets/custom/player/slice/키위.png': { stageId: 'stage3', minScore: 30 },
    'player:image:Assets/custom/player/slice/토마토.png': { stageId: 'stage3', minScore: 50 },
    'player:image:Assets/custom/player/balls/골프공.png': { stageId: 'stage1', minScore: 30 },
    'player:image:Assets/custom/player/balls/농구공.png': { stageId: 'stage3', minScore: 10 },
    'player:image:Assets/custom/player/balls/럭비공.png': { stageId: 'stage3', minScore: 30 },
    'player:image:Assets/custom/player/balls/배구공.png': { stageId: 'stage3', minScore: 50 },
    'player:image:Assets/custom/player/balls/야구공.png': { stageId: 'stage1', minScore: 60 },
    'player:image:Assets/custom/player/balls/축구공.png': { stageId: 'stage2', minScore: 30 },
    'player:image:Assets/custom/player/balls/테니스공.png': { stageId: 'stage2', minScore: 60 },
    'ring:color:#ff3b3b': { stageId: 'stage1', minScore: 60 },
    'ring:color:#ff5ca8': { stageId: 'stage1', minScore: 60 },
    'ring:color:#ff9b2f': { stageId: 'stage1', minScore: 60 },
    'ring:color:#ffe44d': { stageId: 'stage1', minScore: 60 },
    'ring:color:#a6ff4d': { stageId: 'stage1', minScore: 60 },
    'ring:color:#7cd4ff': { stageId: 'stage1', minScore: 60 },
    'ring:color:#ffffff:glow': { stageId: 'stage2', minScore: 60 },
    'ring:color:#ff3b3b:glow': { stageId: 'stage2', minScore: 60 },
    'ring:color:#ff5ca8:glow': { stageId: 'stage2', minScore: 60 },
    'ring:color:#ff9b2f:glow': { stageId: 'stage2', minScore: 60 },
    'ring:color:#ffe44d:glow': { stageId: 'stage2', minScore: 60 },
    'ring:color:#a6ff4d:glow': { stageId: 'stage2', minScore: 60 },
    'ring:color:#7cd4ff:glow': { stageId: 'stage2', minScore: 60 },
    'obstacle:color:#ff3b3b': { stageId: 'stage1', minScore: 10 },
    'obstacle:color:#ff5ca8': { stageId: 'stage1', minScore: 20 },
    'obstacle:color:#ff9b2f': { stageId: 'stage1', minScore: 30 },
    'obstacle:color:#ffe44d': { stageId: 'stage1', minScore: 40 },
    'obstacle:color:#a6ff4d': { stageId: 'stage1', minScore: 50 },
    'obstacle:color:#7cd4ff': { stageId: 'stage1', minScore: 60 },
    'obstacle:image:Assets/custom/obstacle/꼬깔콘.png': { stageId: 'stage1', minScore: 10 },
    'obstacle:image:Assets/custom/obstacle/드릴.png': { stageId: 'stage1', minScore: 30 },
    'obstacle:image:Assets/custom/obstacle/벼.png': { stageId: 'stage1', minScore: 50 },
    'obstacle:image:Assets/custom/obstacle/야채피자.png': { stageId: 'stage1', minScore: 60 },
    'obstacle:image:Assets/custom/obstacle/얼음.png': { stageId: 'stage2', minScore: 10 },
    'obstacle:image:Assets/custom/obstacle/옵시디언.png': { stageId: 'stage2', minScore: 30 },
    'obstacle:image:Assets/custom/obstacle/이끼.png': { stageId: 'stage2', minScore: 50 },
    'obstacle:image:Assets/custom/obstacle/치즈피자.png': { stageId: 'stage2', minScore: 60 },
    'obstacle:image:Assets/custom/obstacle/페퍼로니.png': { stageId: 'stage3', minScore: 30 },
    'obstacle:image:Assets/custom/obstacle/추가건/검.png': { stageId: 'stage1', minScore: 180 },
    'obstacle:image:Assets/custom/obstacle/추가건/기계뿔.png': { stageId: 'stage3', minScore: 50 },
    'obstacle:image:Assets/custom/obstacle/추가건/소용돌이.png': { stageId: 'stage3', minScore: 20 },
    'obstacle:image:Assets/custom/obstacle/추가건/강아지.png': { stageId: 'stage1', minScore: 30 },
    'obstacle:image:Assets/custom/obstacle/추가건/고양이.png': { stageId: 'stage1', minScore: 50 },
    'obstacle:image:Assets/custom/obstacle/추가건/라쿤.png': { stageId: 'stage2', minScore: 30 },
    'obstacle:image:Assets/custom/obstacle/추가건/래서판다.png': { stageId: 'stage2', minScore: 60 },
    'obstacle:image:Assets/custom/obstacle/추가건/웰시코기.png': { stageId: 'stage3', minScore: 30 },
    'obstacle:image:Assets/custom/obstacle/추가건/양.png': { stageId: 'stage3', minScore: 60 },
    'obstacle:image:Assets/custom/obstacle/추가건/악마양.png': { stageId: 'stage1', minScore: 180 },
  },
};
